name: CI/CD # Workflow 이름
on: # Event 감지
  push:
    branches:
      - main
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: Generate build # React Build
        run: yarn build

      - name: Deploy # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{secrets.AWS_REGION}}
          S3_BUCKET_NAMEL: ${{secrets.S3_BUCKET_NAME}}
        run: |
          aws s3 sync ./build s3://$S3_BUCKET_NAME --region $AWS_DEFAULT_REGION
